/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author NguyenNgocDang
 */
public class QuanLyChuyenXe_Form extends javax.swing.JFrame {
    ArrayList<ChuyenXe> list_xe = new ArrayList<>();
    int vitri = 0;
    /**
     * Creates new form QuanLyChuyenXe_Form
     */
    public QuanLyChuyenXe_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_machuyen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_tentaixe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_soxe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_doanhthu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_loaixe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_sokm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_sotuyen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_noiden = new javax.swing.JTextField();
        tf_songaydi = new javax.swing.JTextField();
        bt_luu = new javax.swing.JButton();
        bt_xemlui = new javax.swing.JButton();
        bt_xemtoanbo = new javax.swing.JButton();
        bt_thoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_hienthi = new javax.swing.JTextArea();
        bt_xemtoi = new javax.swing.JButton();
        bt_save = new javax.swing.JButton();
        bt_open = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Thông tin chuyến xe");

        jLabel2.setText("Mã chuyến: ");

        jLabel3.setText("Tên tài xế:");

        jLabel4.setText("Số xe:");

        jLabel5.setText("Doanh thu:");

        jLabel8.setText("Loại xe:");

        jLabel9.setText("Xe nội thành:");

        jLabel6.setText("Số tuyến: ");

        jLabel7.setText("Số KM:");

        tf_sotuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sotuyenActionPerformed(evt);
            }
        });

        jLabel10.setText("Xe Ngoại Thành:");

        jLabel11.setText("Nơi đến:");

        jLabel12.setText("Số ngày đi:");

        tf_songaydi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_songaydiActionPerformed(evt);
            }
        });

        bt_luu.setText("Lưu");
        bt_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luuActionPerformed(evt);
            }
        });

        bt_xemlui.setText("Xem lùi");
        bt_xemlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xemluiActionPerformed(evt);
            }
        });

        bt_xemtoanbo.setText("Xem toàn Bộ");
        bt_xemtoanbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xemtoanboActionPerformed(evt);
            }
        });

        bt_thoat.setText("Thoát");
        bt_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thoatActionPerformed(evt);
            }
        });

        ta_hienthi.setColumns(20);
        ta_hienthi.setRows(5);
        jScrollPane1.setViewportView(ta_hienthi);

        bt_xemtoi.setText("Xem tới");
        bt_xemtoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xemtoiActionPerformed(evt);
            }
        });

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_open.setText("Open");
        bt_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_openActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(242, 313, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3)
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_tentaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_soxe, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_machuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_open)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_luu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)))
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 323, Short.MAX_VALUE)
                        .addComponent(bt_xemtoanbo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_xemlui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_xemtoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_thoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_sokm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tf_sotuyen)
                            .addComponent(tf_songaydi)
                            .addComponent(tf_noiden))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_machuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_sokm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_tentaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_soxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tf_sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_luu)
                            .addComponent(bt_xemtoanbo)
                            .addComponent(bt_xemlui)
                            .addComponent(bt_thoat)
                            .addComponent(bt_xemtoi)
                            .addComponent(bt_save)
                            .addComponent(bt_open))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_noiden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tf_songaydi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_sotuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sotuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sotuyenActionPerformed

    private void tf_songaydiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_songaydiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_songaydiActionPerformed

    private void bt_xemtoanboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xemtoanboActionPerformed
        // TODO add your handling code here:
            ta_hienthi.setText(" ");
        for (ChuyenXe xe:list_xe){
        
            ta_hienthi.append(xe.toString()+"\n");
        }
    }//GEN-LAST:event_bt_xemtoanboActionPerformed

    private void bt_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bt_thoatActionPerformed

    private void bt_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luuActionPerformed
        // TODO add your handling code here:
        vitri++;
        if(tf_loaixe.getText().toString().equals("1")){
            XeNoiThanh noi = new XeNoiThanh();
            noi.setMaso(tf_machuyen.getText().toString());
            noi.setTaixe(tf_tentaixe.getText().toString());
            noi.setSoxe(tf_soxe.getText().toString());
            noi.setDoanhthu(Long.parseLong(tf_doanhthu.getText().toString()));
            noi.setSotuyen(Integer.parseInt(tf_sotuyen.getText().toString()));
            noi.setSokm(Float.parseFloat(tf_sokm.getText().toString()));
            list_xe.add(noi);
            ta_hienthi.setText("Đã thêm thành công: "+tf_machuyen.getText().toString());
        }else{
            XeNgoaiThanh ngoai = new XeNgoaiThanh();
            ngoai.setMaso(tf_machuyen.getText().toString());
            ngoai.setTaixe(tf_tentaixe.getText().toString());
            ngoai.setSoxe(tf_soxe.getText().toString());
            ngoai.setDoanhthu(Long.parseLong(tf_doanhthu.getText().toString()));
            ngoai.setNoiden(tf_noiden.getText().toString());
            ngoai.setSongaydi(Integer.parseInt(tf_songaydi.getText().toString()));
            list_xe.add(ngoai);
            ta_hienthi.setText("Đã thêm thành công: "+tf_machuyen.getText().toString());
        }
    }//GEN-LAST:event_bt_luuActionPerformed

    private void bt_xemtoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xemtoiActionPerformed
        // TODO add your handling code here:
            ta_hienthi.setText(vitri++ + "");
                if(vitri<list_xe.size()-1){
            if(list_xe.get(vitri).getClass().getSimpleName().equals("XeNoiThanh")){
                XeNoiThanh xe = (XeNoiThanh)list_xe.get(vitri);
            
                tf_machuyen.setText(xe.getMaso());
                tf_tentaixe.setText(xe.getTaixe());
                tf_soxe.setText(xe.getSoxe());
                tf_doanhthu.setText(xe.getDoanhthu()+"");
                tf_sotuyen.setText(xe.getSotuyen()+"");
                tf_sokm.setText(xe.getSokm()+"");
            
        }else{
                XeNgoaiThanh xe = (XeNgoaiThanh)list_xe.get(vitri);
            
                tf_machuyen.setText(xe.getMaso());
                tf_tentaixe.setText(xe.getTaixe());
                tf_soxe.setText(xe.getSoxe());
                tf_doanhthu.setText(xe.getDoanhthu()+"");
                tf_sotuyen.setText(xe.getNoiden()+"");
                tf_sokm.setText(xe.getSongaydi()+"");                
            }
        }else if(list_xe.size()==0)
            ta_hienthi.setText("Chưa có chuyến xe nào mời nhập mới.");
        else
            ta_hienthi.setText("Không tới được nữa.");
    }//GEN-LAST:event_bt_xemtoiActionPerformed

    private void bt_xemluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xemluiActionPerformed
        // TODO add your handling code here:
        ta_hienthi.setText(vitri-- + "");
        if(vitri>0){
            if(list_xe.get(vitri).getClass().getSimpleName().equals("XeNoiThanh")){
                XeNoiThanh xe = (XeNoiThanh)list_xe.get(vitri);
            
                tf_machuyen.setText(xe.getMaso());
                tf_tentaixe.setText(xe.getTaixe());
                tf_soxe.setText(xe.getSoxe());
                tf_doanhthu.setText(xe.getDoanhthu()+"");
                tf_sotuyen.setText(xe.getSotuyen()+"");
                tf_sokm.setText(xe.getSokm()+"");
            
        }else{
                XeNgoaiThanh xe = (XeNgoaiThanh)list_xe.get(vitri);
            
                tf_machuyen.setText(xe.getMaso());
                tf_tentaixe.setText(xe.getTaixe());
                tf_soxe.setText(xe.getSoxe());
                tf_doanhthu.setText(xe.getDoanhthu()+"");
                tf_sotuyen.setText(xe.getNoiden()+"");
                tf_sokm.setText(xe.getSongaydi()+"");                
            }
        }else if(list_xe.size()==0)
            ta_hienthi.setText("Chưa có chuyến xe nào mời nhập mới.");
        else
            ta_hienthi.setText("Không lùi được nữa.");
            
    }//GEN-LAST:event_bt_xemluiActionPerformed

    private void bt_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_openActionPerformed
        // TODO add your handling code here:
                JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView());
        int returnvalue = jfc.showOpenDialog(null);
        if(returnvalue == JFileChooser.APPROVE_OPTION){
            File selectedfile = jfc.getSelectedFile();{
            try{
                FileInputStream fis = new FileInputStream(selectedfile.getAbsoluteFile());
                ObjectInputStream ois = new ObjectInputStream(fis);
                list_xe.removeAll(list_xe);
                do{
                    list_xe.add((ChuyenXe)ois.readObject());
                }while(ois.equals("\0"));
                    ois.close();
                JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex) {
                    JOptionPane.showMessageDialog(null, "Lỗi lưu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuanLyChuyenXe_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        }
    }//GEN-LAST:event_bt_openActionPerformed

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        // TODO add your handling code here:
                JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView());
        int returnvalue = jfc.showSaveDialog(null);
        if(returnvalue == JFileChooser.APPROVE_OPTION){
            File selectedfile = jfc.getSelectedFile();{
            try{
                FileOutputStream fos = new FileOutputStream(selectedfile.getAbsoluteFile());
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                for (int i=0; i<list_xe.size();i++)
                    oos.writeObject(list_xe.get(i));
                    oos.close();
                JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex) {
                    JOptionPane.showMessageDialog(null, "Lỗi lưu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
        }
        }
        
    }//GEN-LAST:event_bt_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenXe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenXe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenXe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenXe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyChuyenXe_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_luu;
    private javax.swing.JButton bt_open;
    private javax.swing.JButton bt_save;
    private javax.swing.JButton bt_thoat;
    private javax.swing.JButton bt_xemlui;
    private javax.swing.JButton bt_xemtoanbo;
    private javax.swing.JButton bt_xemtoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_hienthi;
    private javax.swing.JTextField tf_doanhthu;
    private javax.swing.JTextField tf_loaixe;
    private javax.swing.JTextField tf_machuyen;
    private javax.swing.JTextField tf_noiden;
    private javax.swing.JTextField tf_sokm;
    private javax.swing.JTextField tf_songaydi;
    private javax.swing.JTextField tf_sotuyen;
    private javax.swing.JTextField tf_soxe;
    private javax.swing.JTextField tf_tentaixe;
    // End of variables declaration//GEN-END:variables
}
